### ISSUE TITLE
proposal to introduce new commands to Hide all Input Cells and Unhide all Input Cells.

### ISSUE THREAD

**Issue by lvch** [andrejv/wxmaxima#310]
I have a troubles in WxMaxima with appearance of my expressions:
![is0](https://f.cloud.github.com/assets/6746594/2243775/617986c0-9d33-11e3-8f65-17954a85cdf8.gif)
![is1](https://f.cloud.github.com/assets/6746594/2243779/6bbe956c-9d33-11e3-84e6-6cc139f02a91.gif)
![is2](https://f.cloud.github.com/assets/6746594/2243782/704a1b74-9d33-11e3-9506-844c0477a058.gif)
![is3](https://f.cloud.github.com/assets/6746594/2243783/7311896e-9d33-11e3-80d3-31122521d82a.gif)
Namely:
1. I'd like to have a possibility to hide and unhide ALL input cells.
The problem is that I like to keep the 'hidden' view,
but after 'Evaluate All Cells' (Ctrl-R) command all input cells
became in unhidden state. (I'd like to preserve 'hidden' view,
because it is more suitable for publications.) So, to close
all cells I must click on rectangle (at top left corner of the cell)
to close every cell. This is very inconvenient.
If number of cells is significant, I must spent significant time for this.

Before hand I defined function for output of expressions, in the first line:
n_eq(a):= if a='% then print("->      ",ev(a)) else print("(",a,")   ",ev(a))$

and the function for output of lists is:
n_eq_transpose(a):= print(if a='% then "->      " else concat("(", a,")   "), transpose(ev(a)))$

So, I propose to introduce to Wxmaxima 2 new commands:
Hide all Input Cells and Unhide all Input Cells

Here is the file http://black.pu.ru/lvch/LL_1_en.wxm
1. Input cells always shows the first line, even in hidden state.
   So, to display nothing meaningful, I have to place empty comments:
   /\*   _/
   at the first line. So, in hidden state I see only something:
   (%i4)  /_   */...  (2 lines hidden)

Would it be possible to implement the appearance of 'hidden' cell such way,
that not display even the first line?

**Comment by gunterkoenigsmann** [comment]
Did understand this ticket wrongly and did add the possibility to hide the input cells on html and TeX export.

**Comment by lvch** [comment]
I'd like to have a possibility to hide and unhide ALL input cells

**Comment by gunterkoenigsmann** [comment]
I still hoped that the main problem is that the input cells are shown 
in the exported worksheet, too.
But we already moved 2 steps into the direction you asked us to:
 - With 15.04 hidden input cells stay hidden when the "evaluate all 
cells" button has been pressed
 - And we can export everything without the hidden cells.

For next step the code leaves many options. I cannot seem to find a 
good option, though:
 - I could implement a button that completely hides all input calls and 
one that renders all hidden input completely visible again. But to the 
unexperienced user it would be non-obvious how to get a worksheet into 
a working order again and I don't want to scare users by making half of 
the data they have worked on for hours suddenly disappear. Also having 
two hide functions would add a bit of redundancy to the GUI.
 - I could make the "fold" function for input cells make the input cell 
disappear completely. But I cannot think of a obvious way to make the 
input cell appear again that feels enough to "work like magic" that I 
would like to include it into my normal workflow.
 - A button that when clicked somehow changes its icon to something the 
user knows he has to click on in order to make the input cells visible: 
Similar things already have mysteriously failed to work on Windows and 
I cannot think of a icon that actually tells the user he wants to click 
at it.

Currently on my computer I have changed the text of all input cells to 
"light gray" in order to somehow make the input less visible than the 
output and made the output to be displayed in bold.

Do you have any idea here how this function could look like?

Kind regards,

  Gunter.
