### ISSUE TITLE
Interrupt button does interrupt current calculation, not the current command.

### ISSUE THREAD

**Issue by robert-dodier** [andrejv/wxmaxima#338]
I am copying bug report #2771 verbatim from the Maxima bug tracker (https://sourceforge.net/p/maxima/bugs/2771/) as it involves wxMaxima and not Maxima itself. Hope this helps.

-----------------------------------
wxMaxima version: 13.4.0
Maxima version: 5.31.1
Maxima build date: 2013-09-24 09:49:12
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.8

The most humiliating thing about maxima and the same problem was in the commercial version of Macsyma. First the interrupt command is practically useless.
NOt only that one cannot even restart maxima as it gives NO control whatsoever to the keys in many situations. Why is an interrupt done atleast once a second
or even every 10 seconds at the longest to give control to the keyboard so one can restart maxima. But no it just keeps on calculating and getting ready or printing out.
It happens again and again and the only way to get out of it is to ctrl-alt-delete and start task manager. This happens again and again. Practically NEVER does
the interrupt do anything at all. And less than 10% of the time does 'restart maxima ' respond and there is NO way to stop it from endless time taking to printout
or parsing output etc etc or printing out. Nothing responds - no keys , no mouse, nothing. As I know I have done assembly language programming and there is a way to do interrupts
and give control to the keyboard.

**Comment by gunterkoenigsmann** [comment]
I assume the latter: After the data has been read from maxima and wxMaxima is formatting it the user has to wait for wxMaxima having finished this process: Since wxWidgets is doing things in a strict sequential way there is no easy way to add the ability to interrupt things here. After the last 3 month's patches this probably is no more needed, though, for many (but of course not all) problems since the speed of the layout process has been greatly increased.

**Comment by dilijev** [comment]
Just being faster doesn't solve the underlying problem. If this is indeed because we don't have a separate thread on standby to interrupt processing, maybe this is something we can take action on anyway. I assumed this issue was strictly related to how the stream from Maxima was being processed.

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

You are right: It doesn't solve the problem but merely does scale it.
Anyway: Since wxWidget is based on sequentially processing a event
queue the only way I know of we could support an interrupt action for
drawing objects would be moving MathCell::DrawList() to the idle loop
and drawing only a limited number of objects before we wait for being
called again. But I still hope there is another way.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQJ8BAEBCgBmBQJU4YyXXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuO5rIQAKWVzB+kQtgfT1bngrfXJ9+n
VMPWQdc7H9ByjTarWmHmbt95yjxxc9pWUUL9C1Fh8Znm9O1hcrGWTKOHtsFIMG3n
cqVV/ehg9t3VkmX9/jqva3X9/KZ1XMnPFLblGoBbG3d9YBQGzGqEURnEPZ4cnf6+
OEKO2X7gTu6br6YhIebNB+Vx6c9mn2tS70olxUymAkrl8UUgYaKfMs0Y6MF/osBT
QDbiiJiSaRpJA35HmsSAxA9W8P76ho41tfdDoRzA2qDUqzE1T9rtdbz9+yMeFjXD
Mn9WrcYMs0OZcLaweUdxJ6fXvlKm0xogWMBXNnxIG+5pmD0/xr6VYyyNfCdZt46S
GsNLWKpcm+2jnkvR/v4bgQn/tYh6XKn+B3QFzoXnQ8VyOWoNmbA6olGz9BWJGvQw
S17xdUpZfI2vgkgUnBq7+ZeyFf/fashEpQFVikDrp78yvlKtTO2CLiSScdsEC19g
ogRZ3CFn3H+pMOe8EqPonxZnXY+tEbyRxyetgVRBRQQ59i8TaKOOTYtr/lT0dM+T
r8LA68ZBuz7ykx9g7AJQyh6T2a9Dn1WzgHm4EAXk6h9MJEh8NjUObSO3FIDauxf9
MCBvyGUbhSk9slIMSbGgTO/9uanMCaoA4QIAvMCB+09t+w5IiglOJUAtddZGOuhv
pvyJB+4L/5bxY+VrHrZX
=A3Pf
-----END PGP SIGNATURE-----

**Comment by gunterkoenigsmann** [comment]
Did do additional testing. There is no way to interrupt maxima in the "reading maxima output" phase, too.

**Comment by robert-dodier** [comment]
I don't usually use wxMaxima, and in this issue I've just copied a problem found by another user, but I can guess what the problem is. Well, there are at least 2 problems, and actually I think it will require some work on the part of both Maxima and wxMaxima to resolve them.

(1) Maxima runs in a single thread
(2) Maxima doesn't pay attention to the socket which delivers input from wxMaxima

Problem (2) means that there's no way to tell Maxima "hey, stop what you're doing" by, say, reading a special value from the socket or detected a closed socket and reopening it.

Problem (1) means that problem (2) can't be solved because Maxima can't compute a result and pay attention to the socket at the same time.

This is a pretty serious problem, but it's possible that we can make progress on it if we put our heads together (both Maxima and wxMaxima as I was saying).

**Comment by zmth** [comment]
I was the original poster. When i said ' interrupt ' I meant and stated in the assembly language code directly controlling the microprocessor NOT any higher level compiled or code translated into assembly language and certainly not lisp. The best and efficient code is always done at the assembly language level no matter how long and drawn out that may be.

**Comment by gunterkoenigsmann** [comment]
You are right that assembler is the most direct and cpu-efficient way 
to do things and that using assembler generally allows one to do 
everything the operating system doesn't prevent. Big parts of the 
windows, the linux and the Mac Os kernel therefore have been converted 
to assembler.

In this case using assembler is no practial way to go, though, since 
things that are written in assembler have generally to be re-done once 
for every architecture they run on. wxMaxima now runs on many 
processors, at least on
 - ia32
 - amd64
 - arm32
 - arm32-thumb
 - arm64
 - m68k
and we might receive the interrupt signal from the user not by actually 
by the means of an interrupt but from many different systems:
 - Windows device drivers
 - over the network from X11
 - from ibus
 - from the wayland library and
 - from unity

Anyway I think in the meantime we should have eliminated all places 
where wxMaxima isn't responsive for long enough that the user will be 
affected by this. The only thing that still has to be done is to teach 
maxima to listen to signals of wxMaxima regardless what maxima is doing 
and to teach it how to exit from any subprogram and where to jump if it 
gets such a signal. But this is out-of-scope for wxMaxima since  this 
has to be done in the maxima project.
Actually the first part of this task has been done, too: We can send a 
signal to the lisp interpreter that runs maxima at any time and it will 
in this case interrupt the current loop. But this loop can still be an 
inner loop of a command, not the whole command the user has typed in. I 
don't know enough about lisp, though, to tell if this can be extended 
to a functionality that automatically returns to the command prompt.

Kind regards,

   Gunter.

**Comment by gunterkoenigsmann** [comment]
I think the wxMaxima side of this issue should be resolved now: Pressing Ctrl+G seems to always interrupt the current maxima command. There are some cases, though, where the command doesn't return to the command-line but to the lisp loop it was called from => This loop might call the next maxima command automatically and therefore not return to an input prompt. Don't know if that can be helped on the maxima side => Files https://sourceforge.net/p/maxima/bugs/3107/ and will close this bug on this side for now.
