### ISSUE TITLE
linsolve: there are no () in output when copy the text

### ISSUE THREAD

**Issue by Ferikusu** [andrejv/wxmaxima#463]
wxMaxima 14.09.0 running in Fedora 21

input
linsolve([3x+z=10,5x-y-z=16],[x,y,z]);
output
See PNG attached

But when I copy it in mode text and paste it in another line:
[x=-%r1-10/3,y=-(8*%r1-2)/3,z=%r1]
there are no () in x
The correct text should be
x=-(%r1-10)/3

**Comment by gunterkoenigsmann** [comment]
This issue is corrected in wxMaxima 15.04. Current .deb images can be downloaded at https://code.launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies but they will contain a bug that can crash the session for the next about 90 minutes. If needed it is not too hard to compile wxMaxima from source, though.
