### ISSUE TITLE
Clicking "Check for updates" does nothing

### ISSUE THREAD

**Issue by dossan** [andrejv/wxmaxima#480]
I want to update wxMaxima to the latest version, and when I click "Check for updates" (under Help) nothing happens, not even a dialog pops up. Is this a known problem?

How can I update correctly wxMaxima on `Mac OS X`? 

I have been using a Mac OS X for almost a year, but I am still not understanding how installation and uninstallations work... it seems it depends on the program or app, and usually programs do not provide an explanation on how to uninstall or upgrade them, and usually we need to do it.

**Comment by gunterkoenigsmann** [comment]
On Linux this button seems to work.

Uninstalling apps on OS X sometimes is quite a beast: In theory an app is a zip archive that should contain everything that is needed for running this app. In the case of maxima and wxMaxima this is true so just deleting the app removes the app save the configuration dialogue settings - that don't cost enough disk space that one would care. If the app sometimes wants the system to trigger actions when the app isn't running, though, the app has to publish this by putting stuff into the Libraries folders. Some apps clean them up again when they are deleted. Some don't. I think this is one of the very few things on a mac that are slightly broken by design. In other words: Just delete the old wxMaxima from the applications folder and put a new one there instead. But don't trust other apps to handle upgrading this easy.
