### ISSUE TITLE
wxMaxima crashes in integrating evaluation

### ISSUE THREAD

**Issue by JunjieCai** [andrejv/wxmaxima#486]
I tested the cases in "10 minutes wxMaxima tutorials"

When I evaluate most of them, the wxMaxima crashes and stops responding, but they work fine if I evaluate them in xMaxima

--------a list of failed cases-------------------
integrate( sin(x), x);
integrate( sin(x), x, 0, %pi);

integrate( 1 / (x^2 + a), x);

assume(a > 0)$
integrate( 1 / (x^2 + a), x);
forget(a > 0)$

A: matrix([1,-1],
          [1,sin(c)]);
B: invert(A);
A.B;
ratsimp(A.B);

assume(omega > 0);
ode2( 'diff(y, t, 2) + omega^2 * y = 0, y, t );
ic2(%, t = 0, y = amp, 'diff(y,t) = 0 );

 
------------------------My system information--------------
wxMaxima version: 15.4.0
Maxima version: 5.36.1
Maxima build date: 2015-05-02 09:23:10
Host type: i686-pc-mingw32
System type: Microsoft Windows 6.1 Build 7601 (Workstation) x86
Lisp implementation type: Clozure Common Lisp
Lisp implementation version: Version 1.9-r15764  (WindowsX8632)

**Comment by gunterkoenigsmann** [comment]
Did try to reproduce the problem on my computer using both the official release and the git version. Seems like I cannot reproduce the cash here. But will try to get hold of a windows computer.

In most of the above examples wxMaxima doesn't have to draw something strange. For example the integrals are solved before wxMaxima has to display them. My guess is that your version of maxima, not of wxMaxima is broken in a way and the integrals therefore aren't solved. Could you try to reproduce some of the failed examples from command-line or from xMaxima to verify that?

Thanks a lot,
and kind regards,

     Gunter.

**Comment by FredCai** [comment]
I did try all of the cases in xMaxima, but the xMaxima worked fine.

Thanks and regards

**Comment by gunterkoenigsmann** [comment]
Weird.

Another idea: If it is wxMaxima perhaps the bug is one of the ones I fixed since the release. Could you replace the wxMaxima folder of your maxima installation by the contents of http://wolfgang.dautermann.at/maxima/wxmaxima-daily-win.zip and test again? The current nightly build has two issues:
 - It cannot playback animations until I finished debugging this part.
 - And the .exe file it contains currently doesn't show the application's icon.

But it contains many small fixes and enhancements.

Kind regards,
Gunter.

**Comment by FredCai** [comment]
Thanks, I tried it. But the problem still exists.

Regards

**Comment by andrejv** [comment]
Please try your examples with a different display algorithm.

Enter

    set_display('none)$

or

    set_display('ascii)$

before executing the problematic input.

**Comment by FredCai** [comment]
Cool, all the failed cases work well after set_display('none)$

Thanks a lot

**Comment by andrejv** [comment]
Do you have the jsMath fonts enabled/installed? Try disabling them in the Style tab. Maybe change the fonts used.

**Comment by gunterkoenigsmann** [comment]
Did add the information that this might be the cause for a crash to the 
Troubleshooting section of the offline help.

**Comment by FredCai** [comment]
Hi andrejv, I tried changing fonts remedy but it didn't solve the problem

Thanks

**Comment by FredCai** [comment]
I tried installed jsMath fonts downloaded from this page

http://www.math.union.edu/~dpvc/jsmath/download/jsMath-fonts.html

It solved the problem I met at the beginning.

I think it's a better solution since set_display('none) or set_display('ascii) can only provide a ugly presentation for complex math expressions

Regards

**Comment by JohnHuang-China** [comment]
Thank you! I solve it in the same way.
jsMath fonts must be installed from
http://www.math.union.edu/~dpvc/jsmath/download/jsMath-fonts.html
and we must select "Use jsMath fonts".

I hope that the dear developer could solve this problem so that we could us wxMaxima without jsMath fonts using limit.That we will have a choice!
