### ISSUE TITLE
Shortcut for restarting Maxima

### ISSUE THREAD

**Issue by mardukbp** [andrejv/wxmaxima#488]
I frequently have to restart Maxima in order to delete all bindings. That way I do not pollute my notebook with `kill(all)`. Having a shortcut would make it faster than typing that command.

**Comment by gunterkoenigsmann** [comment]
Did have the same problem => The toolbar button is already there in the current git version.

**Comment by mardukbp** [comment]
Pardon the insistence. I am more of a keyboard-centric user. I would really prefer to have a keyboard shortcut.

**Comment by gunterkoenigsmann** [comment]
Which one feels logical to you? Perhaps we can find one we don't need to publish because it is intuitive enough. Ctrl+backspace cannot be used since it already means: delete word.

Am 5. Juni 2015 07:27:50 MESZ, schrieb "Marduk Bolaños" <notifications@github.com>:
>Pardon the insistence. I am more of a keyboard-centric user. I would
>really prefer to have a keyboard shortcut.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/488#issuecomment-109167327

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mardukbp** [comment]
What about `Ctrl Alt R`?

**Comment by gunterkoenigsmann** [comment]
This shortcut doesn't look like being prone to be hit accidentally. If Andrej doesn't veto I think I will implement it next week and put it into the documentation.

Am 5. Juni 2015 17:25:37 MESZ, schrieb "Marduk Bolaños" <notifications@github.com>:
>What about `Ctrl Alt R`?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/488#issuecomment-109327592

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by mardukbp** [comment]
Great! Thank you!

**Comment by gunterkoenigsmann** [comment]
Did speak to soon: Ctrl+R already triggers the "re-evaluate all cells" 
function and does do so if Shift is pressed, too.
Ctrl+Shift+Delete? This incorporates the delete key that already hints 
a deletion. Ctrl+Alt+Delete won't work as it sometimes is configured to 
restart the X server.

Kind regards,

   Gunter.

**Comment by gunterkoenigsmann** [comment]
CLosed with commit 1c303e960afad245646ba2080bccd6426cf70e69.

**Comment by mardukbp** [comment]
Ctrl+Shift+Delete is fine. Thanks!

**Comment by mardukbp** [comment]
As for the shortcut for restarting Maxima, what about `Ctrl-F1`?

**Comment by gunterkoenigsmann** [comment]
Why something containing F1? F1 for me is reserved to help menu 
specific things.
I would have come up with Ctrl+R, but Ctrl+R already stands for 
re-evaluate, not for restart. Ctrl+Shift+R? Don't know if this one 
feels logical.
Anyway:

If you found a suitable shortcut just add it to the text of the 
following line of wxMaximaFrame.cpp:

      APPEND_MENU_ITEM(m_MaximaMenu, ToolBar::menu_restart_id,
                       _("&Restart Maxima"), _("Restart Maxima"), 
wxT("gtk-refresh"));

If you have changed a translatable string it would also be nice if you 
included the new string into the list of translatable ones by doing a

    make allpo

afterwards you can edit locales/es.po in order to update the spanish 
translation  -
...and send us a patch. I will then do the german translation, too.



Kind regards,

   Gunter.

**Comment by mardukbp** [comment]
Ctrl-Shift-R is fine. Actually, I do everything computer-related in
English. I have a Spanish keyboard because it is difficult to find an
English keyboard in Mexico. Anyway, I see that the Spanish translation
of wxMaxima needs some work. I will finish it and fix it and send a pull
request.
