### ISSUE TITLE
Delete cell with keyboard

### ISSUE THREAD

**Issue by mardukbp** [andrejv/wxmaxima#489]
Being a keyboard-centric user I find it tiresome having to click on the cell bracket in order to delete it. It would be nice to be able to delete a cell with the cursor anywhere inside it.

**Comment by gunterkoenigsmann** [comment]
If you press the backspace key when the current cell does no more contain text you should have the requested effect. You could also replace the press on the bracket by selecting a cell with shift+the cursor keys.

At least this works on my computer.

**Comment by mardukbp** [comment]
Using backspace for empty cells is fine, but using shift + arrows for multiline cells is not very efficient.

**Comment by gunterkoenigsmann** [comment]
Did read the question again and I suppose the problem is that there is 
no single-key shortcut for deleting cells. My own approach for deleting 
a cell from the keyboard is the key combination


    Ctrl+a
    Backspace
    Backspace

If this combination is too long I could theoretically add a shortcut 
and document it by including it into the cell menu. But this menu is 
already rather long so I will be not too easy to convince to do this.

**Comment by mardukbp** [comment]
Thanks! That's good enough.
