### ISSUE TITLE
Please document the wxMaxima and Maxima versions of all releases

### ISSUE THREAD

**Issue by jondo** [andrejv/wxmaxima#505]
Otherwise I cannot find out the name of the historic installer for wxMaxima 13.04.2.
(I want to use exactly this version to process old wxmx files.)

**Comment by gunterkoenigsmann** [comment]
Why on earth would you want to do that? If newer versions of wxMaxima don't work with your files please tell us what has happened so we can fix it.

**Comment by jondo** [comment]
I want to hand over a set of wxmx files to a colleague, and I want to be sure that all of them work for her exactly the same as when they were created - without testing them one by one.

**Comment by gunterkoenigsmann** [comment]
Was afraid to have missed a critical bug. Phiew!

The long answer is:

The current version of wxMaxima *will* open the file correctly (we are proud of that). Actually wxMaxima currently is even backwards-compatible: Any old wxMaxima will be able to process .wxmx files created with any new wxMaxima version, too.
The next version will bring a new feature (sub-sub-sections) that isn't supported by older wxMaxima versions. But even that won't hinder older versions of the program from opening the files: They will interpret sub-sub-sections as the next sectioning level they support (subsections) - and correctly handle the rest of the files.

The only thing that tends to change behavior from time to time is maxima itself: Even if this program has a long history it is still evolving quite fast. 

I personally would tell my colleague to use the newest version of maxima and wxMaxima: wxMaxima 13.04 still had many bugs and stability issues that have been fixed since then and still had no undo function for cell deletes. In the improbable case that maxima has changed behavior in a way that breaks anything maxima version 13.04 will work for your files: The first part version number is the year of the release, the second part is the month - and the third number is the number of urgent bugfix releases that had to be made after releasing an official version of the program.
It would be possible, too, to install both 13.04 and 15.04 on your collegue's computer at the same time: Two versions of maxima or wxMaxima don't interfer with each other - and in the configuration diaogue one could even instruct wxMaxima 15.04 to use maxima 13.04 instead of maxima 15.04 if this is ever necessary. But I hope that this isn't really necessary.

**Comment by jondo** [comment]
Thank you for your detailed answer! I will recommend the newest wxMaxima version to my colleague. The wxmx contain the old output anyway, so she can compare with the recomputed output.
