### ISSUE TITLE
Store configuration and cache according to XDG specifications

### ISSUE THREAD

**Issue by genodeftest** [andrejv/wxmaxima#561]
In the old unix days applications stored all their configuration dirs and files in hidden directories under the users home dir. These worked well enough back then, since there weren't many applications storing stuff there. Nowadays however, there's typically about a hundred files and dirs in the users homedir.
The freedesktop organization took it into their hands to change this, and wrote a specification how to handle such data which can be found at: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
I propose that wxMaxima follows the same guidelines, to remove the clutter from users homedirs by incorporating the basedir-spec as set by the freedesktop org, which would bring the config files into .config (the default for $XDG_CONFIG_HOME) .cache for caches etc.

**Comment by gunterkoenigsmann** [comment]
A good description and a reasonable and quite complete request - 
but this time I would like to ask you if you could file it at http://wxWidgets.org, instead: wxMaxima doesn't handle the configuration storage itself but relies on wxWidgets to do so. wxWidgets is very handy since it works as a wrapper around the function the current operating system provides (be it Windows, be it OS X or Linux) and provides a platform-independent ways to do nearly everything you want. Since it tends to be easier-to-use than the actual functions the platform provides it is quite popular - which means:
if wxMaxima fixes the problem we have loads of architecture-dependent code. If wxWidgets corrects it  about 30 applications would profit from that.

=> closing the request not because it is somehow bad or invalid but hoping that you forward it to wxWidgets: My last searches for dconf or gconf on http://trac.wxwidgets.org seemed to indicate that nobody has done so until now.

**Comment by gunterkoenigsmann** [comment]
Did take a second look at the problem:

If they don't want to use gconf or dconf as backend I assume there might be a way of talking them 
 - to change the way the filename for the config file is constructed out of the name of the app and the name of the vendor
 - and think about a way of automatically migrating the configuration file to its the new location on opening it: wxFile should provide all methods needed to move the file and for probing if this needs to be done.

Kind regards,

       Gunter.

**Comment by genodeftest** [comment]
Ok, there is an upstream ticket at http://trac.wxwidgets.org/ticket/9300. Thanks!
