### ISSUE TITLE
A lot of plot files

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#617]
Each time a new plot is generated, a new plot-file is stored in in the Windows directory c:/users/<user>/

The file are numbered separately like e.g. "maxout_12168_47.png" 
Soon the user will end up having hundredths of *.png - files in the user directory.
- Is this by intention ? 

Best regards
Rene'

**Comment by gunterkoenigsmann** [comment]
Partially: The old behavior was that if two wxMaxima processes ran 
concurrently they used the same file names and therefore the images 
from both instances were mixed / some instanced issued errors / the 
data from both processes was mixed causing hybrid images.


The .png files should disappear, though, once they have been included 
into the worksheet...

**Comment by ReneSci** [comment]
Could it be when a user only uses  "*.wxm" - files for a long time - and
not *.wxmx ?

Best regards
Rene'


2015-11-16 19:04 GMT+01:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

.wxmx should be rock solid with wxmaxima 15.04 and later. But - this
error was a general one. I did introduce it when trying to make image
handling more efficient. But it should be fixed in the current git
source of wxMaxima.

Kind regards,

      Gunter.

On 16.11.2015 22:50, Rene Hansen wrote:

.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQJ8BAEBCgBmBQJWSlEJXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuO1kIP/1t4txpmD1GEm1P69fVSQCHa
tfX0hHM+vTRDP3OLPw5FMTYdSbUPwJjU4pxUMnA1bZRmJ6Vt8pHa0oSmsyKZs3cj
0tFqfxGim9g23QcV3veHjY/MVT9WaEjseS8dwOLYw0h34ku9AnKcmc+PuGP5WMnH
T7jB4RJtZiY+je3CSjarKiAK7paG4ouI53qdvc/9w/MkoWCt8Bjr+9gyIoRFFXE7
EhooQ6KIe1ftT5exk7wnz1ykIZgp8gAFhfHkqAxAdVZSBZQiOMEQ1dGVX3bsPf7z
r8Ez0d0ITQQ6hoSvWT/0GzvB/UGojop5QyJRs/ZG3HbDZOziK7Rp61mTsCYCWbrX
XVrx0oz1NayKXIFM3mfhvmmUiMrt2QrFwtJSbwYKZwZ7l/Ok7eWv5edvUv5YonL5
XkuholtW/pzi36c9YcjMq+5p63B8edY5kQYbDqQ2rIjlMuDc/4GTkcJOJDdcJ5g/
4NF64LWMSd/veN/pSGQ1FbY5EURMTtPmiZ74w1KfhqqpuDlkzHXS3zifeQZofu5a
uvqFxV/6qij6+Wq186oKtQosKOLv9JLW325whOYvcbvUO5W83IlL31V0rxKXRaOp
zyLG9TnDjLLI+qXlMlHj1Q8dy24v81F4Ksm6DCz6ZVcDzxvXQMsYpdVU/Pll71XW
SHDkm95XxBtMa9U6IsuY
=CYH7
-----END PGP SIGNATURE-----

**Comment by gunterkoenigsmann** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

.wxmx should be rock solid with wxmaxima 15.04 and later. But - this
error was a general one. I did introduce it when trying to make image
handling more efficient. But it should be fixed in the current git
source of wxMaxima.

Kind regards,

      Gunter.

On 16.11.2015 22:50, Rene Hansen wrote:
> Could it be when a user only uses "*.wxm" - files for a long time
> - and not *.wxmx ?
> 
> Best regards Rene'
> 
> 
> 2015-11-16 19:04 GMT+01:00 Gunter Königsman 
> <notifications@github.com>:
> 
>> Closed #617 <https://github.com/andrejv/wxmaxima/issues/617> via 
>> becd465
>> 
> <https://github.com/andrejv/wxmaxima/commit/becd4656c068ee33ed9e9859032f0c3e005505d7>
>>
>
> 
.
>> 
>> — Reply to this email directly or view it on GitHub 
>> <https://github.com/andrejv/wxmaxima/issues/617#event-465743620>.
>>
>
>>
>> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/andrejv/wxmaxima/issues/617#issuecomment-157181630>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQJ8BAEBCgBmBQJWSlEQXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOIkAP/AlV1v/tlR81qf5CJYLH0Ww7
iqr/UQI3/SZIvrScDUZmhJDiR7vRCZjofHzX1RYnPOee/y/o3KqWNfBBgs8lslSe
mouEzE/khcKkxY25aWCPGf97NRdnL7V2oX1Cp4eMo1/WM0woKg8mv2rv+l+FFqJN
SjJkUrZuRXg69YNWC/0RQP5mr+SqhzlHY2au816GeY+FVWXx5OaqLFS6vtUWGGeA
tyFz0YoO/vYNSawGb2tbycs961uJXQ9CS+2EJzWZCOqW7DJS1vFdyz4nL8QV+0/d
TBlu5bC1UHI8RWZwQ0yRWBPREp7M3cCHb2Y/VXtrtpOacqaXGis+LctNDpJ8caMI
8/uw1yT/J1EtbwIRnta/mxVJBCg+cqbO1BdKlmkTKQo6TJNPCFCueQ5g4ZJGD9xi
gwM7yXBTXFZUU9cEOj4jsZ5SeRo1fc4nYImDJq1kZ0U9s3MZB6nPkpFR48J2u+dj
sBHtmxoRxkgSUf0qyakMhuEhswqugHA9uxsyFCG8gukxWDvCPoUYtMtMTN6O9fny
3LTwZXPK4ODcl8uskHAai/PYGHAYR5K1rGpDC3wSrfaBYxgqWxG6pGifGZY7ASR4
vdtk9tDK8rRt8aiI7ZkCWOG4Wb1/e/qRkfqvqb/zXxt3PmzXr8pc6+lxnNahwii2
J3c4jAfz+Aq5n3K8TKKX
=9wJ8
-----END PGP SIGNATURE-----
