### ISSUE TITLE
Null space of complex matri 

### ISSUE THREAD

**Issue by OlivierBauchau** [andrejv/wxmaxima#643]
Define the following complex matrix
Lci: matrix([%i*kappa,     0,     0, 0,     0,     0],
           [0,     %i*kappa,-kappa, 0,     0,     0],
           [0, kappa,     %i*kappa, 0,     0,     0],
           [0,     0,     0, %i*kappa,     0,     0],
           [0,     0,     0, 0,     %i*kappa,-kappa],
           [0,     0,     0, 0, kappa,     %i*kappa]);
nullspace(Lci);
"Proviso: "notequal(%i*kappa,0) and notequal(-kappa^2,0)
(%o10) span(matrix([0],[%i*kappa^2],[-kappa^2],[0],[0],[0]))

It seems that this command returns only one of the two vectors of the null space.
another vector in the null space is
span(matrix([0],,[0],[0],[0][%i*kappa^2],[-kappa^2]))

**Comment by gunterkoenigsmann** [comment]
Arrgh! Seems like I didn't actually send my answer after writing it.
The we both are using is split into two packages: maxima (the program that does do the actual work) and wxMaxima (the graphical user interface). This division makes sense in the way that it keeps both projects small enough that the respective team can handle them. But sometimes it is not trivial (even for developers) to determine which project a bug is in / can be best resolved in.

This time I would like you to ask the maxima project (maxima.sourceforge.net) instead: Seems like wxMaxima correctly sends the data to maxima and correctly displays the reply. Let's hope that they can help you.

Will close this ticket: Not because I think it is invalid but in the hope that it can be solved in the maxima project instead.

Kind regards,

     Gunter.
