### ISSUE TITLE
Warnings are not suppressed on opening wxmaxima by double click on a .wxm file

### ISSUE THREAD

**Issue by RolandSalz** [andrejv/wxmaxima#671]
1.	In maxima-init.mac I reload suprv1.lisp (in order to redefine the function $print). This being done under sbcl on the console, I get a heap of warnings due to redefining the functions that are being defined in this file. If I start wxmaxima with an empty worksheet, these warnings don't show up, which is good. They don’t show up either, if then I load any existing .wxm file from the file menu, which is also good.

2.	But if I start wxmaxima by double click on an existing .wxm file, I do get all the warnings in red letters from having loaded the suprv1.lisp, appended at the end of the last cell, without having done anything with this file yet. And I get them again and again on each opening of other worksheets (and thus starting new wxmaxima screens/sessions). This is bothering and I consider this to be a bug, because this behavior is different from 1).

**Comment by RolandSalz** [comment]
Just found out that the problem has an even mor serious dimension: "Evaluate all cells" does not work properly any more once I have received any such warning on opening wxmaxima."Evaluate all cells" just stops somewhere in the middle and shows me this initial warning again. Its impossible to run through the whole file with the evaluation.

**Comment by andrejv** [comment]
Uncheck the `Abort evaluation on error` option in the `Maxima` section of the configuration dialog.

**Comment by RolandSalz** [comment]
Thank you, that solves the problem described in my yesterday's comment.

**Comment by rend3r** [comment]
I think im found some strange side effects.
1st case:
1) Start WxMaxima.
2) Open wxm from recent files menu.
3) Evaluate all visible cells.
![wx_ev11](https://cloud.githubusercontent.com/assets/12601181/13903092/5646feda-ee7c-11e5-926b-aee1db07cfed.png)
%i1 has appeared in 1st cell.
4) Evaluate all visible cells once again.
![wx_ev12](https://cloud.githubusercontent.com/assets/12601181/13903096/a857335c-ee7c-11e5-948b-d73322a9b8f2.png)

2nd case. 
1) Open wxm by double click.
![wx_ev2](https://cloud.githubusercontent.com/assets/12601181/13903103/f55c8bf2-ee7c-11e5-968a-bd72d7bfa808.png)
%i1 has appeared in last cell.
2) Evaluate all visible cells.
%i1 has appeared in 1st cell and disappeared in last (same as 1 case 3 step).
3) Evaluate all visible cells.
Same as 1 case 4 step.

**Comment by andrejv** [comment]
This issue with (%o1) lines should be fixed in maxima after

https://sourceforge.net/p/maxima/code/ci/9825941312b70d9fd06443cd54a8a8e867f807d4/

**Comment by RolandSalz** [comment]
Having loaded the 5.38.1 installer recently I can see that the problem I mentioned Feb 25 still remains.

**Comment by gunterkoenigsmann** [comment]
Ok... ...I think I have understood the problem now:
maxima-init.mac causes maxima to output warnings and potentially error messages. These warnings are sent to the worksheet and therefore mark it as "changed". But since there still is no GroupCell to attach them to they cannot be displayed. The fact that error messages got lost has lead to hours of debugging on my side and many questions to the mailing list.

In the meantime I have added code that if a message needs to be displayed and there is no cell to attach it to an empty cell is created and the message is attached to this cell. This means that important messages no more get lost.

The 2nd half of the problem has affected me, too, many times: Warnings that cannot be avoided, cannot be suppressed, if we don't count a hacky
     
     with_stdout("C:/Users/thomas/maxima/temp.tmp",load(lapack))$;
     
...and that have no practical relevance. I am convinced maxima will do something about them one day. But first a magical idea is needed, what might be the right solution on maxima's side.

=> Will close this report as the inconsistency is fixed. But I am not happy with the bogus warnings, neither, not knowing how to avoid them in the right way.
