### ISSUE TITLE
Unsaved status after loading wxm document

### ISSUE THREAD

**Issue by rend3r** [andrejv/wxmaxima#686]
After loading wxm by double click immediately get asterisk without any document changes.
https://github.com/andrejv/wxmaxima/issues/659

**Comment by gunterkoenigsmann** [comment]
Cannot reproduce this on my system => there seems to be a second factor to be needed in order to reproduce this bug. Normally if a bug can be reproduced reliably on Andrej's or my computer fixing it is only a matter of minutes. If we don't have a minimal working example, though, we need much luck, though => If you have any idea what this 2nd factor might be we would be grateful.

**Comment by rend3r** [comment]
I can reproduce with any wxm on my system. Path to wxm contains latin symbols only.

**Comment by andrejv** [comment]
@rend3r 
Can you provide the output of `wxbuild_info()`?

**Comment by rend3r** [comment]
@andrejv 
(%i1) wxMaxima version: 15.8.0
Maxima version: branch_5_37_base_489_gb2332bc_dirty
Maxima build date: 2016-02-12 16:33:10
Host type: i686-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.3.2

I'v notice asterisk appears immediately after %i1 lines draw https://github.com/andrejv/wxmaxima/issues/671#issuecomment-198858357

**Comment by andrejv** [comment]
The patch which solves #659 was committed after 15.08 release, which you are using. You can update to the latest nightly or wait for the next release.

**Comment by rend3r** [comment]
@andrejv 
>You can update to the latest nightly or wait for the next release
I am already using latest nightly
Look at screencast what's happening [out.zip](https://github.com/andrejv/wxmaxima/files/184987/out.zip)

**Comment by gunterkoenigsmann** [comment]
Should be resolved in 17.10. Feel free to re-open this issue if this is wrong.
