### ISSUE TITLE
wxMaxima hang occurs  after input "solve([(x-x0)/(x1-x0)=s],[x])"

### ISSUE THREAD

**Issue by sagasm** [andrejv/wxmaxima#687]
wxMaxima version: 15.8.2
Maxima version: 5.37.3
Maxima build date: 2016-01-11 20:53:44
Host type: i686-pc-mingw32
System type: NIL NIL NIL
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.11

**Comment by gunterkoenigsmann** [comment]
Weird:

On my system (wxMaxima version: 15.8.0
Maxima version: branch_5_37_base_503_g7f0f60c
Maxima build date: 2016-03-20 07:04:21
Host type: x86_64-unknown-linux-gnu
System type: 
gcc -falign-functions=4 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O -falign-functions=4 -DENABLE_UNICODE -DDYNAMIC_FFI -DDYNAMIC_MODULES -I.  -lreadline -lncurses -ldl /usr/lib/libavcall.so /usr/lib/libcallback.so  -lsigsegv libgnu_cl.a 
SAFETY=0 TYPECODES WIDE_HARD GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.10
libreadline 5.2
libffcall 1.11 GNU C 4.8.2 X86_64
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built 3605577779) (memory 3667442664)) I get the following output:

     [x=s*x1+(1-s)*x0]

The same happens if I compile maxima using gcl. My guess would be that the problem has been solved in the git master of wxMaxima or Maxima without being found first.

Do you get any error message? Or does wxMaxima still react but stay in the "maxima is calculating" mode?

**Comment by sagasm** [comment]
No errror message.wxMaxima loses response.

**Comment by gunterkoenigsmann** [comment]
Then we can hope that the current nightly windows build of wxMaxima (http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly) solves the problem. If it doesn't we need to hope for the next "real" release of maxima or for Wolfgang to release the nightly build of wxMaxima, too - unless you want to give the instructions in http://andrejv.github.io/wxmaxima/develop.html a try and try to build maxima yourself.

Kind regards,

    Gunter.

**Comment by gunterkoenigsmann** [comment]
For 17.10 I have found (and resolved) many issues in the XML reader => Am confident that the problem no more exist. Feel free to re-open the ticket if that isn't true.
