### ISSUE TITLE
"solve([x^2+y^2=1, (x-2)^2+(y-3)^2=9],[x,y]);" returns "[]"

### ISSUE THREAD

**Issue by sagasm** [andrejv/wxmaxima#690]
wxMaxima version: 15.8.0
Maxima version: 5.37.3_5_g8106b41_dirty
Maxima build date: 2015-11-14 16:49:58
Host type: i686-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on 158234.vs.webtropia.com [127.12.34.56])

**Comment by gunterkoenigsmann** [comment]
I think I found it out:

     solve(x^2+y^2=1,y);

has 2 solutions which normally indicates that the whole system of equations has several solutions that all only work within specific regions of [x,y].  Solve instead searches for a solution that is valid for all x and all y.

The only way I know of solving this problem is

- Take a problem with n equations and n variables
- First solve one equation for one variable
- pick a solution that ends up in the region you want a solution for and introduce it into the rest of the equations.

The result is n-1 equations with n-1 varuables... ...and repeat this approach until the whole problem is solved.

There might be better approaches. If you want you can ask the maxima-discuss mailing list on maxima.sourceforge.net about them: 

. Normally they are exceptionally quick to respond. The actual mathematics is done by maxima whereas wxMaxima only outputs the solutions and collects the input - which makes it hard for users to tell where to report a problem (Sometimes it is hard for the project admins, too), but makes each program small enough that a small team can actually support it. 

Will close this ticket for wxMaxima hoping it can be more efficiently handled by the maxima project.

Kind regards,

    Gunter.

**Comment by robert-dodier** [comment]
Submitted the the Maxima bug tracker as: https://sourceforge.net/p/maxima/bugs/3150/

**Comment by gunterkoenigsmann** [comment]
Thanks a lot!

   Gunter.
