### ISSUE TITLE
Inappropriate Japanese translation (localization) in menu

### ISSUE THREAD

**Issue by ayoko** [andrejv/wxmaxima#692]
Hello.

Recently I (re-)started to use wxMaxima 15.04.0 on Mac OS X, and found some inappropriate Japanese translation (or localization) in a menu (or dialog).
We see the following menu for Integration, but some technical terms should be replaced.
![japanese_integrate](https://cloud.githubusercontent.com/assets/128388/14161981/da289e4e-f722-11e5-9b67-e644becbbfce.png)
The term "差出人" should be "下限" (lower limit).  A direct translation of "From" is "から", but "から" is usually placed after a number (e.g. "0 から" or "-pi から"), so "下限" should be much better.
As similar, "宛先" should be "上限" (upper limit).
For your convenience, I also attach a corresponding English dialog.
![english_integrate](https://cloud.githubusercontent.com/assets/128388/14162068/a372916a-f723-11e5-8445-bb5b16f8e00d.png)

Thanks and Best Regards,
Atsushi

**Comment by gunterkoenigsmann** [comment]
Dear Atsushi-San,

I seem to fail to find the said string in the japanese translations of the current development build that can be accessed according the instructions found at http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly. This might be good news (since it could mean that the bug is already resolved) or just mean that neither my emacs nor my gedit did handle my search right.

But any help is as always welcome: The current version of the translations can be found at https://github.com/andrejv/wxmaxima/blob/master/locales/ja.po and as you can see loads of things are missing or marked as "fuzzy" which means that the machine did try to update the translation hoping that the result will be correct. Both are mainly due to me having changed and added loads of strings in the source of wxMaxima. If you find anything we can do better the best way is to send us a patch to this file or to create your own fork of wxMaxima on github and then to click on the "send a pull-request" button which automates the process of sending patches.
If you are using windows a program that is good in dealing with patches and with git as a storage for program code and translations is tortoisegit, on linux I am using rabbitvcs - if you happen to use a mac I have no idea how to do these things. But normally on a mac there is a way. If there isn't telling us which version of the file you did correct (the current version is 6853743a9039a27038bde867b73ab985abcf4319, which github abbreviates to 6853743) and sending us the updated file should work, as well.

Thanks a lot,
and kind regards,

  Gunter.

**Comment by ayoko** [comment]
Hello Gunter,

Thank you for your prompt and helpful suggestions.

When I looked at the locales/ja.po, I found the following lines:

#: ../src/IntegrateWiz.cpp:37 ../src/Plot2dWiz.cpp:37
../src/Plot2dWiz.cpp:47
#: ../src/Plot2dWiz.cpp:536 ../src/Plot3dWiz.cpp:36 ../src/Plot3dWiz.cpp:45
#: ../src/SumWiz.cpp:33 ../src/wxMaxima.cpp:3604 ../src/wxMaxima.cpp:4025
msgid "From:"
msgstr "下端："

and also

#: ../src/IntegrateWiz.cpp:41 ../src/Plot2dWiz.cpp:40
../src/Plot2dWiz.cpp:50
#: ../src/Plot2dWiz.cpp:539 ../src/Plot3dWiz.cpp:39 ../src/Plot3dWiz.cpp:48
#: ../src/SumWiz.cpp:36 ../src/wxMaxima.cpp:3604 ../src/wxMaxima.cpp:4026
msgid "To:"
msgstr "上端："

I guess that the translations have been already fixed at the current
development.
The Japanese words "上端" (upper end) and "下端" (lower end) look fine.

Once again, thank you for your help very much.

Best Regards,
Atsushi Yokoyama,
Kanagawa Japan


On Thu, Mar 31, 2016 at 2:23 PM, Gunter Königsman <notifications@github.com>
wrote:

> Dear Atsushi-San,
>
> I seem to fail to find the said string in the japanese translations of the
> current development build that can be accessed according the instructions
> found at http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly.
> This might be good news (since it could mean that the bug is already
> resolved) or just mean that neither my emacs nor my gedit did handle my
> search right.
>
> But any help is as always welcome: The current version of the translations
> can be found at
> https://github.com/andrejv/wxmaxima/blob/master/locales/ja.po and as you
> can see loads of things are missing or marked as "fuzzy" which means that
> the machine did try to update the translation hoping that the result will
> be correct. Both are mainly due to me having changed and added loads of
> strings in the source of wxMaxima. If you find anything we can do better
> the best way is to send us a patch to this file or to create your own fork
> of wxMaxima on github and then to click on the "send a pull-request" button
> which automates the process of sending patches.
> If you are using windows a program that is good in dealing with patches
> and with git as a storage for program code and translations is tortoisegit,
> on linux I am using rabbitvcs - if you happen to use a mac I have no idea
> how to do these things. But normally on a mac there is a way. If there
> isn't telling us which version of the file you did correct (the current
> version is 6853743
> <https://github.com/andrejv/wxmaxima/commit/6853743a9039a27038bde867b73ab985abcf4319>,
> which github abbreviates to 6853743
> <https://github.com/andrejv/wxmaxima/commit/6853743a9039a27038bde867b73ab985abcf4319>)
> and sending us the updated file should work, as well.
>
> Thanks a lot,
> and kind regards,
>
> Gunter.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/andrejv/wxmaxima/issues/692#issuecomment-203756484>
>



-- 
Yokoyama, Atsushi
