### ISSUE TITLE
batch input

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#698]
Hi All,
I reported a while ago that WxMaxima 5.36.1 was able to use lines of code written in the wxm file as inputs to a batch file that requests more information, like this:
batch(new_cartan_test4)$
[x,y,z]$
[1,1,1]$
[x,y,z]$
done$
The subsequent lines to the batch calling are provided as information and the program continues.
This was no longer true for 5.37.1: the program just waits for more information disregarding the lines.
I was told that this was fixed but I just tested 5.38.0 and the same problem still remains.
Thanks,
Daniel Volinski

**Comment by gunterkoenigsmann** [comment]
Then I misunderstood the bug report. 

...and I can explain the change in wxMaxima's behavior: Old versions sometimes lost track which output cell belongs to which input cell, which lead to all kinds of confusion => I changed the input and output routines so that new input is only sent to maxima only after it has processed a new command. wxMaxima therefore knows which cell the output it got was for (the last input cell it sent to maxima) and there is no more the danger of input cells ending up as the answer to questions which was a common error source for my files:
Cells following a question were interpreted as input only if evaluation stopped directly after a question. Otherwise they would be used as the answer. It never occurred to me that this could be used as a feature, as well...

Sometimes a way of automatically answering maxima's questions would be handy, though, admittedly, even if I would prefer to have this feature in maxima, not in wxMaxima... ...don't know if asking the maxima developers if that would be possible would be a good idea.

Kind regards,

 Gunter.

**Comment by danielvolinski** [comment]
Hi Gunter,
In my opinion this is a very important feature: It enables the user to write the answers to the questions inside the file, without having to write the answer again and again every time you use the file.
Please find a way to return this functionality to WxMaxima, I use this feature a lot.
Otherwise I will be condemn to stay in 5.36.1 forever ...
Thanks a lot
Daniel

**Comment by gunterkoenigsmann** [comment]
I'm no more sure that the thing can be resolved this way:

- I can mark cells as "lines of this cell can be used as answers".
- I can even send these lines line per line to maxima and keep track which piece of maxima output belongs to which cell.
- But if a command in the middle of one cell asks a question and a cell marked as containing answers is put below it and evaluated... ...then I always hit cases I find no way to reliably catch.

**Comment by gunterkoenigsmann** [comment]
I feel sorry to have to admit that in the meantime I had to drop my original approach entirely:

 - The worksheet can be added to the evaluation queue in an arbitrary order.
 - There is no way to determine if a line is meant as a command or a answer, especially as on re-evaluating the same worksheet the number of questions asked by maxima might change.
 - It is impossible to highlight which lines are meant as answers and which are meant as commands, as we don't know that ourselves - which makes the worksheet harder to read.

There was no way to get a consistent user experience this way.

But you need a way to provide answers for questions and your bug report made me find an elegant way of making wxMaxima remember answers once a question has been answered by the user. They will be printed and formatted like ordinary questions are. Also I've added a checkbox that tells a cell that it can automatically fill in answers allowing the same worksheet to automatically answer some questions and to ask other questions to the user. I hope you can live with this solution.

---

Currently the directory structure of the nightly windows build is broken. But if you don't allow the installer to delete the old installation it will put a working wxMaxima.exe in the wxMaxima/bin folder that already contains the new code.

**Comment by danielvolinski** [comment]
Is this check box you mention above in the last version Maxima 5.41.0?

**Comment by gunterkoenigsmann** [comment]
It should be in the right-click menu. But I am not sure if I added it before 5.41.0 was released or if it was added afterwards...

**Comment by danielvolinski** [comment]
I have wxMaxima 17.10.0 which comes with Maxima 5.41.0.

I open a wxMaxia new file and put in one cell
batch(new_cartan_test4)$
[x,y,z]$
[1,1,1]$
[x,y,z]$
done$

I right click on the cell and I select "Automatically answer questions". The text in the cell becomes italics.
I evaluate the cell, but it still waits for the answers, it does not answers questions automatically!
Is there something I am not doing correctly?
Daniel
