### ISSUE TITLE
Lynda26

### ISSUE THREAD

**Issue by lynda26** [andrejv/wxmaxima#708]
wxMaxima version: 13.4.0 Maxima version 
Maxima version; 5.30.0
Maxima build date:  2013-06-01 21:29:43
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.8

**Comment by gunterkoenigsmann** [comment]
Somehow the information about the actual problem got lost. But as you are using wxMaxima 13.4.0 and many bugs have been fixed since then there is a big chance the issue you are experiencing is no more present in the current version downloadable at http://maxima.sourceforge.net. The current version should also be faster and be able to read files from 13.04 even if 13.04 will regard them as "broken".
