### ISSUE TITLE
How to search on a page of the help manual?

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#714]
Hi All,
I'm looking for the word points_at in the Maxima manual, I click the search tab and write points_at and search in all books, it gets one reference in page drawdf, so I double click on drawdf. Now how can I search the word points_at in this page?

Thanks,
Daniel Volinski

Using: build_info(version="5.38.0_dirty",timestamp="2016-04-03 10:09:05",
host="i686-w64-mingw32",lisp_name="CLISP",lisp_version=
"2.49 (2010-07-07) (built on maxima [192.168.43.2])")

**Comment by gunterkoenigsmann** [comment]
This question isn't easy to answer:

wxMaxima doesn't provide an own help browser. Instead it asks wxWidgets to open one - and wxWidgets normally tries to provide as much contingency from the user's view as possible and uses the functionality offered by the current operating system instead of implementing its own flavor of this functionality. Normally this isn't a bad idea as it makes the application look like a linux program on linux while it clearly resembles a windows application on windows and a native mac application on a mac. But it means that

**Comment by gunterkoenigsmann** [comment]
As I have seen you are using windows: I think microsoft doesn't provide its users with a search functionality that really makes sense. If you own a good pdf reader I therefore would advice you to use the pdf manual from http://maxima.sourceforge.net instead which is searchable. Don't know if one can file feature requests to Microsoft.

**Comment by danielvolinski** [comment]
But in 5.36.1 this worked fine in WxMaxima in Windows. Can that code work in the latest version?
Daniel
