### ISSUE TITLE
Serious problem with function eigenvectors

### ISSUE THREAD

**Issue by zachilas** [andrejv/wxmaxima#717]
Dear Andrej,
I have a serious problem with the function eigenvectors.
I have used it a lot of times up to now, without any problem.
But in the last version (which is really beautiful and advanced in compare to previous), there is a bug (let me call it) with the eigenvectors.
I have a matrix 4 X 4, which is:
A: matrix(
 [-1,1,0,1], 
 [1,-1,1,0], 
 [0,1,-1,1], 
 [1,0,1,-1]
);
According to the eigenvalues, matrix A has 4 eigenvalues: [[1,-1,-3],[1,2,1]]
The λ = -1 is double. OK?
Then according the matrix theory, and since the matrix is real symmetric, it has to have 4 distinct eigenvectors.
But the corresponding function gives:
[[[1,-1,-3],[1,2,1]],[[[1,1,1,1]],[[1,0,-1,0],[0,1,0,-1]]]]
Even the uniteigenvectors function, gives the same result (only 3 instead of 4 eigenvectors): 
[[[1,-1,-3],[1,2,1]],[[[1/2,1/2,1/2,1/2]],[[1/sqrt(2),0,-1/sqrt(2),0],[0,1/sqrt(2),0,-1/sqrt(2)]]]]

You may repeat the calculations with the example in Manual, chapter 23.
If you enter the matrix:
A2: matrix(
 [0,1,0,0], 
 [0,0,0,0], 
 [0,0,2,0], 
 [0,0,0,2]
);
Then the function eigenvectors give:
[[[0,2],[2,2]],[[[1,0,0,0]]]]
But if you see the result in the manual, there are 2 more eigenvectors!

I would appreciate if you could reply to me as soon as possible, since I have given this exercise to my students with deadline: Sunday, 15/5.

Sincerely,
Loukas

**Comment by gunterkoenigsmann** [comment]
Dear Loukas,

I can at least try do one of the things you require and reply as fast as possible And given that the timeframe is short I have already directly forwarded the problem to the maxima mailing list that can be found at: https://lists.sourceforge.net/lists/listinfo/maxima-discuss
The bad news is that this means you will have to subscribe to the list (https://lists.sourceforge.net/lists/listinfo/maxima-discuss) in order to be able to read the answer and will have to search the list archives if the answer has been provided after I informed the list and before you subscribed to it.

In Open Source it is quite common that a big Systems are split into functionalities that are small enough that one team can handle them. wxMaxima therefore is limited to merely displaying the maths and handling the user input. The real work is done in the background by the program maxima that is kept in a separate process so if it crashes or runs out of memory (modern operating systems support overcommitment so this can happen surprisingly and after a malloc() hoping that some process won't use all of its ressources returned something that looks like a valid pointer).

Kind regards,

   Gunter.

**Comment by zachilas** [comment]
Dear Gunter,

Thanks for your kind help.

But searching in previous posts, I have found that the problem of missing eigenvalues has been found since the pre-previous release of Maxima.

Anyway…

I am looking forward the solution of the problem.

 

Kind regards,

Loukas

**Comment by gunterkoenigsmann** [comment]
Closing this bug for wxMaxima as it now is handled by the maxima team.
