### ISSUE TITLE
Latex output garbled up

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#733]
The pdf file I created from the TeX export is garbled up.
1) The output labels are on the right of the page instead of being aligned to the left.
2) The output is centered on the page, they should be on aligned to the left, after the output label.
3) Input %i2 and %i12 are not as I wrote them, they are garbled up.
4) geod_2 (%t13) is not finished, i.e. not all the output is there.
[test.pdf](https://github.com/andrejv/wxmaxima/files/321918/test.pdf)
[test.zip](https://github.com/andrejv/wxmaxima/files/321920/test.zip)

**Comment by gunterkoenigsmann** [comment]
The centering of equations and putting the label to the right is standard in amxTeX. Don't know how this can be helped. ...But at the other two issues I will look as soon as I have time.

**Comment by gunterkoenigsmann** [comment]
You can use wxdrawdf instead of drawdf if you want to export the graph, too. ...and it seems like for outputting text-only output without equation the solution I have taken isn't the best for all cases: I was the one who told wxMaxima to enclose them in \mbox{} commands so they won't be output in the maths font. But if the text has a label it needs to be inside an equation... ...and sometimes we need linebreaks in front of or after the text  ...let's hope I find a better solution. But I am a little bit lost here if we can find something that automatically is right.

For the equation that is too wide to be displayed in a single line I am a little bit lost, too: wxMaxima didn't do anything here that felt like telling LaTeX not to break lines. Don't know why it sometimes does break lines and sometimes it doesn't.

**Comment by danielvolinski** [comment]
I don't know what is amxTeX but I'm not using it.
In version 5.36.1 this was running OK, that is, the labels and output were aligned left.

**Comment by gunterkoenigsmann** [comment]
amsTeX is a package from the american maths society. It adds many useful symbols to LaTeX, a few useful things like the pmatrix environment - and the possibiliy to change the text of the labels the equation environment will output.

In older versions of wxMaxima we used to create our own labels by hand - which was fine for equations 
 - fit into the current line without colliding with the label
 - that didn't extend to more than one line
 - and if the labels were short. 
And it did make the labels left-aligned, which is nonstandard in TeX and differs from what the equation environment does.

Now I have understood that both ways of adding equation numbers have their advantages.

stackexchange tells me if you change the 1st line of your TeX document to the following:

     \documentclass[leqno]{article}

the labels will be on the left side again.
Hope that helps.

**Comment by danielvolinski** [comment]
I don't see the advantage of having a tag on the output label. A tag is used to refer to it later on in the document, but I don't see this happening. Regarding the input label, my opinion is that it should be verbatim as it was before like this
%%%%%%%%%%%%%%%
%%% INPUT:
\begin{minipage}[t]{8ex}{\color{red}\bf
\begin{verbatim}
(%i2) 
\end{verbatim}}
\end{minipage}
\begin{minipage}[t]{\textwidth}{\color{blue}
\begin{verbatim}
AW1:34.968$P1:75.53$AW2:36.956$P2:24.47$
\end{verbatim}}
\end{minipage}

Daniel
