### ISSUE TITLE
The possibility of openen the gnuplot command window dissapeard

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#745]
Previously, when using draw2d to open/plot in a gnuplot window, it was possible within this window to open another window - the gnuplot command window.

In the new release, it seems like this possibility has gone. 
Is there a way to get it back ?

Best regards
---------------------
wxMaxima version: 16.4.2
Maxima version: 5.38.1
Maxima build date: 2016-06-12 17:13:34
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.4

**Comment by gunterkoenigsmann** [comment]
This functionality was part of gnuplot. It might be the case that the packager of the newest release of maxima for Windows did use an older gnuplot version than the packager of the older version this might be cause of this problem. But Wolfgang normally never uses an old version if the new one can be made work => I assume the right place to report this problem might be somewhere at http://www.gnuplot.info. Normally they are quite willing to help. 

Will close this ticket for wxMaxima, not, because it is invalid, but because we don't have influence on it.

Kind regards,

Gunter.

**Comment by ReneSci** [comment]
Sorry for my wery late reply:
I just checked the gnuplot version. It is the same version included with
the current wxmaxima version  16.04.2 (Gnuplot Version 4.6 patchlevel 6) as
has been working ok together vith wxMaxima verision 15.08.1 git.

Does it give any sense ?

Kind regards
Rene'




2016-07-14 12:47 GMT+02:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment]
I will see if I can get my hands on a computer that uses this gnuplot version.

---

In theory it should be possible to just take the gnuplot folder from any gnuplot installation and to replace the gnuplot folder that came with your maxima installation with it. If you find a windows installer for a version that provides the feature you need this might get everything working for you again.

**Comment by ReneSci** [comment]
I just tried to replace the installed gnuplot (the whole gnuplot directory
under the Maxima directory) with the working version (4.6) . It did not
help nor change anything.

Kind regards
Rene'


2016-08-11 21:19 GMT+02:00 Gunter Königsman <notifications@github.com>:
