### ISSUE TITLE
Calculation of square root multiplied by a number shown in wrong way ( It was wright in previous versions)

### ISSUE THREAD

**Issue by lsanjose2** [andrejv/wxmaxima#765]
VXMaxima version; 16.04.02

![image](https://cloud.githubusercontent.com/assets/21958157/18212126/9fd6180e-7141-11e6-8e64-11d4f22d923a.png)

**Comment by gunterkoenigsmann** [comment]
The way square roots are displayed is detetermined by maxima, not by wxMaxima - even if I have admit that there is next to no possibility for an user to see which of the two programs does do this => I would beg you to resolve to http://maxima.sourceforge.net so this problem can be discussed about.

Unfortunately which way is to be seen as "right" changes from problem to problem - and since maxima just does the maths, but doesn't know which problem lies behind this maths there might be no way to automatically determine which outcome is the right one. Sometimes a rootscontract() does help, though.

Will close this bug for wxMaxima, not, because I have a strong oppinion if something has changed to the worst or not, but because it is better addressed to in a different program.
