### ISSUE TITLE
factor makes always minus in front

### ISSUE THREAD

**Issue by greenscreenflicker** [andrejv/wxmaxima#782]
WxMaxima or Maxima loves to make in minus a front: take this example:

a-b;

factor(%);
returns: -(b-a)

Mathematically correct, but very confusing.
Could you have a look at it?
-Michael

**Comment by tigran123** [comment]
I don't think it is to do with the minus but to do with the ordering of symbols, look:

```
(%i1) ordergreat(a,b);
(%o1)                                done
(%i2) factor(a-b);
(%o2)                                a - b
(%i3) 
```

**Comment by gunterkoenigsmann** [comment]
This diagnosis is correct:

Maxima sends us the terms in an order that might be alphabetical or might be consistent with the output of the previous calculations. This algorithm is quite smart (for example it sorts x, x² and x³ in a sensible order) but sometimes does output things like

      -(a-b)/c

which contains more minuses than I would like it to contain. Unfortunately I don't know if there is a way to avoid this without getting other results ordered in a way that is obviously -suboptimal.

Will close this ticket for wxMaxima - not because I think that it is wrong in any way but because I think it can be addressed better in maxima, not in wxMaxima (this way it would fix maxima-mode, sage, Xmaxima etc. too). I can even acknowledge that this problem is known to the maxima guys as it has been discussed many times in the maxima-discuss mailing list and I can acknowledge that the maxima guys aren't against changing things. All that that is needed is a great idea on how an ordering might look like that would give us better overall results.

Kind regards,

    Gunter.
