### ISSUE TITLE
Export to html is not quite readable by Chrome and Firefox.

### ISSUE THREAD

**Issue by tigran123** [andrejv/wxmaxima#791]
Although I am running the very latest versions of everything (at least Chrome), the html files exported by the latest version of wxMaxima (as opposed to 16.04.2) are not readable. For example,

1. Multiply '*' character is replaced by "\," (which from LaTeX analogy I presume means "quad space") and this is rendered by Chrome literally as "\," which totally messes up all the formulae.

2. "\beta * c" is rendered as "\betac" which Chrome shows in red colour --- presumably this is some kind of syntactic error.

Even the stable 16.04.2 wxMaxima emits strange things like:

```
[β\ensuremath{\ensuremath{>}}0,m\ensuremath{\ensuremath{>}}0,c\ensuremath{\ensuremath{>}}0]
```

which Chrome doesn't understand. The corresponding Maxima code in the cell is simply:

```
assume(β>0,m>0,c>0);
```

**Comment by tigran123** [comment]
Ok, after the above commit the \beta*c is working correctly now. But the "\," is still there and so the output is practically unreadable (compared to the output of wxMaxima 16.04.2 which is okay).

I've installed the latest MathJAX version just a few minutes ago (version 0.3) and it made no difference.

**Comment by tigran123** [comment]
Actually, one thing that the latest version does better than 16.04.2 is that "%e" is rendered as "e" rather than literally as "%e" in 16.04.2. But the "\," spoils it all...

**Comment by tigran123** [comment]
correction: my MathJAX.js is version 2.7.0. But the Chrome MathJAX extension is 0.3. But do I really need this extension? Even if I disable it, nothing apparently changes.

**Comment by gunterkoenigsmann** [comment]
On 18.10.2016 20:27, Tigran Aivazian wrote:
> correction: my MathJAX.js is version 2.7.0. But the Chrome MathJAX
> extension is 0.3. But do I really need this extension? Even if I disable
> it, nothing apparently changes.

Andrej equipped wxMaxima with two options for Math output:
 - Rendering maths as bitmaps and shipping the file with <img> tags that
include them. Unfortunately they will almost always be in the wrong font
at the wrong size, not centered correctly to the line, slow and need
much memory.
 - or generating LaTeX commands that render the equations and including
a javascript snippet that loads MathJaX directly from the MathJaX
homepage. The MathJaX script then scans the whole document and thinks
about how it can be best displayed on the current browser. Normally this
results in right-clickable, drag-and-drop-able equations that can be
scaled to any size and that will match the fonts used in the rest of the
document. Unfortunately MathJaX is big and from time to time will
contain bugs that tend to only appear on certain browsers. My guess
would be that MathJaX is the future.

Since we include MathJaX by hand I wouldn't be surprised if the one
installed in the browser won't do anything. But I am no expert in these
things...

**Comment by tigran123** [comment]
Yes, I understand all this. But what I was saying is that if the emitting `\mbox{\,}` makes the code less portable, then why do it? Adding a tiny bit of space between operands in a product is not such an important thing that makes it worth sacrificing portability, especially since we are talking about the latest/stable Chrome + MathJAX combination, not some ancient Nescape or something :)

**Comment by gunterkoenigsmann** [comment]
If I didn't make an error the "\mbox{}" around the "\," should be gone by now.

**Comment by tigran123** [comment]
So you think the problems are caused by the \mbox{} rather than by "\," itself? Ok, let's test it...

**Comment by tigran123** [comment]
Thank you, yes you are absolutely right. But there is one minor bug there still. I'll retest with the stable wxmaxima and will report the details here.

**Comment by tigran123** [comment]
Ok, this minor bug I speak of is present in both stable and latest git versions, namely, look at these cells in the source wxmx file (I manually prefixed the input with "cellN" labels):

```
cell1: eq : a + b;
(eq): b+a
cell2: eq : eq - b;
(eq): a
cell3: eq : eq^2;
(eq): a^2
```

So, the above is exactly as expected. But now export this trivial wxmx file to html and see what the output looks like:

```
(%i1)	eq : a + b;
b+a                                                                                  (eq)
(%i2)	eq : eq - b;
\tag{eq}\label{eq}a
(%i3)	eq : eq^2;
\tag{eq}\label{eq}{{a}^{2}}
```

So, the first cell exported correctly, but the second and third one produced raw LaTeX output `\tag{eq}\label{eq}{{a}^{2}}`.

**Comment by tigran123** [comment]
Just to clarify: the above bug has nothing to do with "\," issue --- this issue you have fixed already, thank you.

**Comment by tigran123** [comment]
Thank you, yes, your fix works perfectly. Generally, now html export is much better than it was --- just some minor bits are left like #792

**Comment by gunterkoenigsmann** [comment]
When I saw my first html file created after Andrej introduced MathJaX I thought: This is the future. In the meantime I have found out that Doxygen and the IEEE homepage both have jumped on the MathJaX train, too - and Chrome has dropped maths support since MathJaX does a great enough job => I expect to see many improvements to MathJaX over the next few months or years.

**Comment by gunterkoenigsmann** [comment]
Let's hope that this is the last problem that remained. If not feel free
to open new bug reports: Your testing (and the troubleshooting info and
the info how to reproduce the problem your bug reports are always
bundled with) are very valuable for the project. I have now also
activated a function that allows to export Equations to HTML in the
MathML format: These equations are displayed fast and with scalable
fonts. But MathML seems not to be too usable, in the moment: In IE it
has problems with fractions. In Firefox with Equation labels. Chrome I
don't have installed.

**Comment by gunterkoenigsmann** [comment]
You are welcome ;-)

...let's find out where the ensuremath commands come from. I assume as ">" and "<" produce strange symbols in babel I tried to make really sure they are output as the math symbol.
