### ISSUE TITLE
Adding an opening Parenthesis sometimes fails to wrap parenthesis around selected text

### ISSUE THREAD

**Issue by gunterkoenigsmann** [andrejv/wxmaxima#797]
Reported by msat-cont:

write e.g. 1234 in input cell, highlight e.g. 23 and press e.g. "
it results in 1"23"4 on older wxMaxima versions, but it leads to 1"4 now.

Cannot reproduce this on my computer, unfortunately.

**Comment by msat-cont** [comment]
Hi, I've found the reason why it stopped to work in current wxMaxima when having "Match parenthesis in text controls" set off.

The additional checking for that setting option was added at commit <a href="https://github.com/andrejv/wxmaxima/commit/91dba13154dae2b2b387837db24d0bc0aeb13c51">91dba13154dae2b2b387837db24d0bc0aeb13c51</a> (the added check at <a href="https://github.com/andrejv/wxmaxima/commit/91dba13154dae2b2b387837db24d0bc0aeb13c51#diff-34195dbc61c3f6184f0955bd2d0e8f3cR1791">1791 line</a> there).

It was a part of the over-deleting of parentheses in issue #787 though it seems that this part was not necessary to change, since it is not about deleting.

I agree with @tigran123 about the unwanted deletions, though would like to see the inserting-around-highlighting back, since it seems that it was not requested to be constricted.

**Comment by msat-cont** [comment]
PS I humbly changed the current 1800 line of EditorCell.cpp into _if(true)_ at my local clone, and it seems to work correctly to me.

**Comment by gunterkoenigsmann** [comment]
That is a valuable piece of information. Let's hope I have interpreted it right.

**Comment by gunterkoenigsmann** [comment]
Am a little bit lost in the number of possibilities we get here:
 - There are users that don't want to enable the "match parenthesis" feature at all
 - There are users that don't want parenthesis to be highlighted, but matched
 - There are users that don't want parenthesis to be matched, but to be highlighted
 - There are sers that want parenthesis only to be matched if text is selected
...and there are many possible combinations of parenthesis matching.

Don't know if it would be helpful to add separate config items for every aspect of the parenthesis matching functionality: There are many open-source-programs (like inkscape, firefox, thunderbird, hugin and gimp) out there that require a week's intensive work in order to find out what settings one wants to set. And there are other programs that hide all interesting settings behind a "I want the expert config dialogue" button. Until now I have tried to keep the configuration dialogue as small as possible...

**Comment by msat-cont** [comment]
It still does not decouple the 1"23"4 feature from the "Match parenthesis in text controls" settings. Thus I again locally patched the code with the *if(true)* 1804 line at EditorCell.cpp.

I agree that some advanced configuration (alike "about:config" at Firefox), by default hidden from users would be helpful, though expecting it at some later time only.

Here it seems like this feature coupling (see above) was done as an over-reaction to that #787 ticket request. Thus it looks to me that this one line would be better reverted here.

**Comment by gunterkoenigsmann** [comment]
Ok... ...reverted it.

**Comment by tigran123** [comment]
Does this mean that the parentheses deleting bug in #787 is back again? Sorry, I have not followed all the details of the discussion because I am on holiday right now (and also because the present stage of my research is more heavily depending on numerical simulations which I did in C and Python (as doing it in C was about 1200 times faster than in Maxima), but there is still plenty of symbolic stuff which I will do in Maxima, specifically in wxMaxima which I find SO pleasant to work in!)

**Comment by gunterkoenigsmann** [comment]
I hope this time the bug that deletes the parenthesis is fixed. At least i wasn't able to reproduce it any more. But to be completely honest I wouldn't be too unhappy if you would be willing to test if this time I got things right.

**Comment by tigran123** [comment]
Ok, I'll try to test it this evening.

**Comment by gunterkoenigsmann** [comment]
> 
> Here it seems like this feature coupling (see above) was done as an
> over-reaction to that #787
> <https://github.com/andrejv/wxmaxima/issues/787> ticket request. Thus it
> looks to me that this one line would be better reverted here.
>
Ok... ...will do so within a few minutes.

Kind regards,

 Gunter.

**Comment by msat-cont** [comment]
@gunterkoenigsmann Thanks.

@tigran123 The feature here is like this: Write a string in a wxMaxima worksheet, highlight (by mouse or Shift+an arrow) that string (or a part of it), and press e.g. "(" or some another bracket/quotation. And the issue was whether effective presence of this feature should be coupled to (some) settings.

**Comment by gunterkoenigsmann** [comment]
The issue Tigran talked about was that deleting parenthesis deleted additional characters at completely different positions in the input. Now I've re-added the code. But this time it should actually work. At least I hope so...

**Comment by tigran123** [comment]
Yes, the latest git seems to work fine wrt not deleting extra characters when the user deletes the parentheses.
