### ISSUE TITLE
Printing: Paper size selection checkbox is grayed out.

### ISSUE THREAD

**Issue by weingaunity** [andrejv/wxmaxima#807]
Hi,

i remember, that in the past (Windows XP and Win 7) i was able to create suitable PDF with PDF Printers. Now i try to get a print and there are so much issues: Paper format A4 seems to be fixed, scaling prints A4 scaled on A4 (so more white space on right side bottom)...
I'm working now on Ubuntu, same issues...

Where changes done at this point in the past?

I will prefere to provide a way to directly export PDF. I think, many guys will be happy if this will work.
Maybe you can use Formating-Objects (FO-Processor FOP) to do the job for you.

Thx, Klaus

**Comment by gunterkoenigsmann** [comment]
Thanks for this bug report!

I almost never use printing so I've completely overlooked this issue.
Hope it works again in the next nightly build. If it doesn't please complain!

**Comment by weingaunity** [comment]
Hi,
where can i find the correct nightly build?

I tried following: ppa:peterpall/wxmaxima-nightlies
but there seems to be the same issue. No improvement.

Find attached images with the wxmaxima version and the disabled print dialog fields.

Thx. Klaus

![printdialog](https://cloud.githubusercontent.com/assets/16756598/20445169/425e6864-add4-11e6-845a-6e251a8e50cf.png)
![wxmaximaversion](https://cloud.githubusercontent.com/assets/16756598/20445170/42608da6-add4-11e6-8239-9a68ef988c52.png)

**Comment by gunterkoenigsmann** [comment]
It is the right nightly build. But it seems like wxWidgets has changed something: wxMaxima is able to deal with any paper format and doesn't tell wxWidgets that it wants A4 paper.

**Comment by gunterkoenigsmann** [comment]
Have reported this issue to http://trac.wxwidgets.org/ticket/17712

**Comment by gunterkoenigsmann** [comment]
Resolved in the current trunk of wxWidgets.

**Comment by weingaunity** [comment]
how can i use the fix on my PC?

**Comment by gunterkoenigsmann** [comment]
You'll need to do this in 3 steps:

 - open software-properties-gtk
 - tell it to download the repositories for source code
 - and update the package list. Now your system knows what packages you do need in order to compile and install stuff
 - open a terminal and type

     sudo apt-get build-dep wx-common wxmaxima 

Now your system should install a C++ compiler (if it doesn't already contain one) and all .h files, tools and libraries compiling and using wxWidgets and wxMaxima will need.

 - obtain the current git master of wxWidgets and extract it into a directory. The most current development release is too old to contain the fix.
 - open a terminal
 - cd into the directory and type:

     ./autogen.sh
     ./configure --prefix=/usr
     make
     sudo make install

Your system now contains a copy of the development version of wxWidgets. But all your applications will continue to use the wxWidgets version they were compiled with => you need to compile wxMaxima, as well:

 - download the git master of wxMaxima and extract it into a directory
 - open a terminal
 - cd into the directory 
 - type:

     ./bootstrap
     ./configure --prefix=/usr
     make
     sudo make install

Now you have a corrected version of wxWidgets and a wxMaxima installation that uses it.

Kind regards,

     Gunter.
