### ISSUE TITLE
wxMaxima: wrong [page breaks] when printing to PDF 

### ISSUE THREAD

**Issue by robert-dodier** [andrejv/wxmaxima#815]
Migrating this one from the Maxima bug tracker; copied verbatim from https://sourceforge.net/p/maxima/bugs/3253/ by Miroslav Siouf; see also the files attached to the Maxima bug report:

If I print wxm file to PDF (under Windows, using PDFCreator) and insert [page-break] in the wxm-file, the old (original) page breaks persist (i.e. the new page-break does not clear the old/original page breaks). As a result, the output PDF file contains both newly inserted manual [page-break] and original [page breaks] at their original places and the file contains more [page breaks] than necessary.

See the attached files.

Version of my programs:

Windows 7 64-bit, PDFCreator 2.4

wxMaxima version: 16.4.2
Maxima version: 5.38.1
Maxima build date: 2016-06-12 17:13:34
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.4

**Comment by gunterkoenigsmann** [comment]
This one was hard to track down. In the end the reason was:

 - wxMaxima creates a copy of the worksheet, layouts it for the current paper size and breaks the pages.
 - wxMaxima starts the output and on windows each time after outputting a page it calls the idle loop to avoid the "Application is not responding" warning.
 - If anything on the screen has changed the idle loop issues a refresh
 - the screen has changed as the "print" dialogue has disappeared and part of the window needs to be redrawn.
 - and the output that was meant for the screen ends up on paper instead.  

The current nightly build should print correctly on windows, finally.

Thanks for forwarding this issue! ...and if there is another bug in this functionality I haven't yet found please complain!

Kind regards,

   Gunter.
