### ISSUE TITLE
Line Wrap/ Line Breaks

### ISSUE THREAD

**Issue by ckoe-bccms** [andrejv/wxmaxima#822]
Hello everybody,

this is an enhancement request relative to 15.08.2, but I think it also applies to 16.04.

Today I had a problem with copy and paste in wxmaxima. Some input was refused because of unmatched parentheses. Copy and pasting into maxima itself produced no error. I was confused by that for quite some time because it looked right and worked in maxima.

It turns out, that the visible part of the input line including a ";" in wxmaxima was ok. However, after the ";" separated by quite an amount of white space there was trailing garbage which I could not see. The garbage was not visible because it was to the right of the visible line length. Probably it would have been visible by manually scrolling with the scroll bar at the bottom of the wxmaxima main window. But I did not notice. Of course this was my oversight and is probably a fringe case. Anyway.

This leads to the following enhancement request(s) which may be regarded as alternatives:
- Would it be possible to highlight white space/tabs after a ";" on a line ?
- Would it be possible to introduce a setting for a line length (configurable length), so that overly long lines get wrapped around (classical line wrap) ?

Thank you very much for considering this and for developing wxmaxima.

Best Regards

Christof

**Comment by gunterkoenigsmann** [comment]
Hmmm... ...line wrap for code cells is quite demanding as it does involve indentation and every user might have a different indentation scheme than the others. And automatically highlighting the rest of the line feels too distracting to me for solving a fringe case.
If one knows where the problem lies pressing Ctrl+A will highlight it, obviously, but that only helps as soon as the problem is actually solved...
...perhaps one day we will find another solution.

**Comment by ckoe-bccms** [comment]
Hello,

probably this would it even worse from the coding aspect, but having a preference for the line length/wrap might work for indentation preferences. A simple check box "line wrap on/off" would do it. If line wrap is "off" (default value) you get the current behaviour, if it is "on: the line length after which the line wraps is the window width (I assume the widget set communicates the width in characters of the chosen font size of the visible text window).

I agree that highlighting space might be too distracting. Especially as I cannot think of a simple rule to distinguish trailing garbage after a ";" from another wanted input.

What is Ctrl-A supposed to do ? in 13.04.2 it does not appear to do anything. But may be that version is too old ?

An unrelated observation: Some help pages (for example the plotting subsection) of the maxima manual are extremely long. While I probably should suggest a finer structure/ hyperlinks to keywords at the top of the page on the maxima list I would like to ask if it would be possible to add a search function to the help browser in wxmaxima to search words in the contents  of the displayed help page (like in a web browser when opening http://maxima.sourceforge.net/docs/manual/maxima_12.html).

Anyway, thank you very much for considering this !

Best Regards

Christof

**Comment by gunterkoenigsmann** [comment]
13.04 is quite old considering that in a few hours there will be a > 3 1/2 years newer version of wxMaxima available. So I advice you to switch to a newer version if you have the possibility. Since ubuntu is using .deb packages and since Andrej watches that wxMaxima doesn't need exotic dependencies I assume the .deb files from https://launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies should be installable on your system.

---

Adding automatic line-wrap for code will be loads of work so I cannot promise when this is done. But - if I find a better way of auto-indenting "if" clauses... ...perhaps the line-wrap code from comment cells can be tought  to fulfill this task.

Kind regards,

   Gunter.

**Comment by gunterkoenigsmann** [comment]
Ok... ...will still need time, this one. But I have created a git branch named CodeLineWrap that, when finished, will implement this feature.

**Comment by ckoe-bccms** [comment]
Hello,

On Fri, Jan 06, 2017 at 01:36:56AM -0800, Gunter Königsman wrote:
> Closed #822 via 21cf3d1ec88121254d99053937dcbeaf7363e7ec.
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/andrejv/wxmaxima/issues/822#event-913819481

thank you very much, I will try it in the next days !


Best Regards

Christof
