### ISSUE TITLE
Allow "Do you want to save ..." dialogs to be answered using keyboard

### ISSUE THREAD

**Issue by TomasRiker** [andrejv/wxmaxima#827]
The dialog that asks whether you want to save the document before loading a new one or exiting the application should respond to keyboard input. Typically, the "N" key should be "No".

**Comment by gunterkoenigsmann** [comment]
This sounds like a good proposal: Switching to the right button using <tab> and pressing enter is requiring more key presses than necessary and isn't too intuitive which both lowers usability. Also your proposal could be a good idea for a few additional dialogues allowing for "yes" and "no".

As we just take the stock confirmation dialogue from wxWidgets I would ask you to forward the problem to this project, though, as they can fix it once-and-dor-a-- for a big bunch of applications.

Kind regards,
 Gunter.

**Comment by gunterkoenigsmann** [comment]
Looked into the code. In theory we could override the standard dialogue in many places like I did with the find dialogue. But this time it will cause things to be quite complicated: In French Yes is "O", in german "J", in Italian "S" and I am not completely sure if there cannot be a language that uses a "N" as the first letter of "yes" => We would need at least as many translations as there exist translated "Yes" and "No" buttons and we would need to keep this in Sync with wxWidgets.

Also I have found out that  wxWidgets seems not to offer its own "Yes" or "No" dialogues if it can avoid doing so but takes the buttons from the operating system instead in order to make sure that they will always keep to be consistent with the OS. The improvements therefore might need to be made by the operating system's programmers.

...and I've found a practical issue: If an dialogue allows the users to input text and offers a "yes" and a "no" button there needs to be additional logic that disallows the button from stealing chars entered in the text field.

=> I like the idea, but will nonetheless close the issue for wxMaxima as I hope there is a better place it might eventually be implemented in.
