### ISSUE TITLE
Fail to simplify some Radicals

### ISSUE THREAD

**Issue by GFROGER** [andrejv/wxmaxima#832]
It is not a bugg, but it would be nice if radcan function of wxmaxima could be able to simplify the following:
sqrt(40*sqrt(3)+73)
in 
5+4*sqrt(3)
I imagine that it could be done the following way.
sqrt(x*sqrt(n)+y)=(a*sqrt(n)+b).
so n*a^2*b^2=n*x^2/4 & n*a^2+b^2=y
let's say n*a^2=u & b^2=v
then u & v are the solutions of z^2-y*z+n*x^2/4=0 and if the discriminant y^2-n*x^2 is a perfect square those soutions are rational and sqrt(x*sqrt(n)+y) can be simplify by suppressing imbedded radical (of course taking care of signs and whose of the solutions is u or v).
Another nice thing would be that radcan could also simplify:
1/(5+4*sqrt(3))
in
(-5+4*sqrt(3))/23
by multiplying numerator and denominator by -5+4*sqrt(3).

Whay do i ask that ?
I had to solve the following equation:
(8*3^(5/2)-492)*x^2+(190*sqrt(3)+3582)*x-170*3^(5/2)-6606=0
I knew before solving it (by building the equation) that one root was (3*sqrt(3)+9)/2.
Note that, when simplified the way above, the other solution is (2*sqrt(3)+135)/39.
If you solve the equation, you will see that it is not obvious at all !!
It would be really fine if radcan could find those simplified values.
Best regards.
Gérard FROGER

**Comment by gunterkoenigsmann** [comment]
For this problem I would like to ask you to ask at http://maxima.sourceforge.net - which is the project page for the program that does the actual mathematics: In open source it is common that a big program is split into separate projects that are small enough to handle for a given group of individuals. In this case wxMaxima mostly handles the display - Maxima the mathematics - and sometimes it is hard to see which one does what so I apologize in advance that for some bugs forwarding users back and forth between the two teems might be necessary.

Will close this ticket for wxMaxima - not because I think it isn't valid (I don't know enough about radcan to be able to decide this) but because it is better handled by the maxima team.

That means: Perhaps the bug is in the documentation, not in radcan: As far as I remember radcan manages to solve more classes of problems than the rest by assuming that roots and trigonometric functions have only one solution. But I might be wrong in this aspect.  
Kind regards,  
Gunter.
