### ISSUE TITLE
Some of the slider button is not available on the main toolbar

### ISSUE THREAD

**Issue by zaits-forever** [andrejv/wxmaxima#834]
Examples (documentation) of using the slider can not be played. Win 7.

**Comment by gunterkoenigsmann** [comment]
This was my fault. The windows nightly http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly is already repaired (it should be stable enough for production use so it is worth a try, if you want) - and the fix is marked for the next minor release of wxMaxima. Sorry that I cannot do more about that.

**Comment by gunterkoenigsmann** [comment]
Is resolved in the current release.
