### ISSUE TITLE
Can't open files with non-ASCII filenames

### ISSUE THREAD

**Issue by SIvan32** [andrejv/wxmaxima#838]
wxMaxima doesn't open files with cyrillic letters in name like this: _/home/sivan/Документы/test.wxmx_

**./src/common/unichar.cpp(65): assert "Assert failure" failed in ToHi8bit(): character cannot be converted to single byte**

Saving files is working right. But if you try to open file you've saved before, you fail.

Backtrace:
[maxima_backtrace.txt](https://github.com/andrejv/wxmaxima/files/707661/maxima_backtrace.txt)

I'm using wxMaxima 15.08.2 on Linux (Fedora Workstation 22).

**Comment by gunterkoenigsmann** [comment]
Thanks for reporting this: Language specific bugs tend to be hard to find.
In theory this specific bug should be fixed in the current source of wxMaxima. Don't know if fedora allows for .deb packages. If yes you could try if the one from https://launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies works on fedora.

Kind regards,

  Gunter.

**Comment by ciampix** [comment]
Tested. It works now. I think this issue should be closed.

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for Testing!
