### ISSUE TITLE
wxMaxima 16.12.1 Nightly Build for windows crashes when loading large wxmx files

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#841]
(%i1)	wxbuild_info()$
wxMaxima version: 16.12.x-unofficial
	Maxima version: 5.39.0_2_g5a49f11_dirty
	Maxima build date: 2016-12-11 23:21:46
	Host type: i686-w64-mingw32
	System type: Win32 6.1.7601 (Service Pack 1) X86
	Lisp implementation type: SBCL
Lisp implementation version: 1.3.12

**Comment by gunterkoenigsmann** [comment]
Would it be possible for you to send me such a file (github won't let you attach it to this bug report. But wxmaxima at physikbuch dot de will be able to receive any e-mail unless the file is more than abou 15 Megabytes long):
I have completely changed the routines that load files in order to resolve a crash I got a few days ago and I suspect that this has introduced a new error.

**Comment by gunterkoenigsmann** [comment]
I have just found (and corrected) an error that might have caused your problem: 8deb2587e2d539466f0eff86c34f4508f91dd3dd

**Comment by gunterkoenigsmann** [comment]
In 17.10 this kind of issue should no more happen => Closing this issue. But feel free to re-open it if it still arises.
