### ISSUE TITLE
another simplification mode  designed to optimize for visual/computational efficiency?

### ISSUE THREAD

**Issue by cmrdt** [andrejv/wxmaxima#893]
esp since factor, ratsimps don't seem to optimize sections/parts of equations optimally,
lack of internal substituting terms into variables and using nested partial- simplifications
work to hold parts static , and aware of internal facets/forms/equivalents simultaneously, comparisons

whether or not use, cost-function e.g. number of operations,  ? `+-` < `*/` < `^` <,

**Comment by gunterkoenigsmann** [comment]
Simplification is quite a beast as for every task a different way of expressing the same thing can be the best way to describe it and sometimes only a great idea on expressing an equation differently allowed science to solve a problem.

A way to tell factor() not to try to factorize the whole expression but to look which terms it has to ignore in order to make the expression shorter would be helpful for me, too, though.

Sometimes

      scanmap('factor,ratsimp(%));

can do wonders on complex expressions. But there are places in which I have no way to make maxima automatically formulate things in a way that suits my needs, neither so I have to manually tell it what to substitute for what.

Unfortunately I have to forward you with you with this request to https://maxima.sourceforge.net as wxMaxima is the program that handles the user interface but the actual mathematics is done by the separate program maxima.

Will close this request for wxMaxima, but not because I think isn't valid, but because it is easier to resolve it in a different project.

Kind regards,
Gunter.
