### ISSUE TITLE
status bar font is based on system Message Box font

### ISSUE THREAD

**Issue by jeeswg** [andrejv/wxmaxima#896]
E.g. in wxMaxima 5.30, the status bar font is not based on the system Message Box font, in wxMaxima 5.39, it is.

Is there an obscure option in a file somewhere that can be set, or some binary edit that can be made to an exe? E.g. to restore the old behaviour, or to specify a font size, or to specify a different system font (e.g. Caption/SmCaption/Menu/Status).

Thanks for wxMaxima. Thanks for reading.

**Comment by gunterkoenigsmann** [comment]
Thanks for reporting and investigating this!

Unfortunately this time I have to ask you to forward this request to a different project this time: On the status bar font wxMaxima has no real influence. It just tells wxWidgets which string is to be displayed there and wxWidgets tells the operating system what to do. But the guys at https://trac.wxwidgets.org/ are quite helpful and fast in responding to bug reports.

Will close this bug for wxMaxima, not because I think it is invalid, but because it needs to be addressed in a different project. If you report the bug there please tell me about the ticket number so I can track the progress of this issue.

Kind regards,
Gunter.
