### ISSUE TITLE
Spanish updated

### ISSUE THREAD

**Issue by cyphra** [andrejv/wxmaxima#966]
[wxmaxima-17_0_1.es.po.gz](https://github.com/andrejv/wxmaxima/files/1674280/wxmaxima-17_0_1.es.po.gz)

**Comment by gunterkoenigsmann** [comment]
Thanks a lot for these translations!

---

Since 17.0.1 quite a few strings have been added to wxMaxima => if you are willing to translate them the strings whose use is planned for the next version can be found at https://github.com/andrejv/wxmaxima/raw/master/locales/es.po 

Thanks again,
and kind regards,

 Gunter.

**Comment by cyphra** [comment]
[wxmaxima.17_0_1.es.po.gz](https://github.com/andrejv/wxmaxima/files/1679244/wxmaxima.17_0_1.es.po.gz)

**Comment by gunterkoenigsmann** [comment]
Great work!
Thanks a lot!

 Gunter.
