### ISSUE TITLE
wxmaxima crashes when integrating multivar functions (fonts problem?)

### ISSUE THREAD

**Issue by Hale812** [andrejv/wxmaxima#978]
When integrating quite simple function in Windows 7 x64, wxMaxima crashes with unintelligible message, as in the screenshot. The example of the function is in the same screenshot. I am not sure, is the function syntax correct, or not, but crashing is definitely not a correct reaction on exception.

![a](https://user-images.githubusercontent.com/25519954/37128486-c2cab2a0-22bd-11e8-83cf-572676fe30bd.JPG)

I have no idea where that "Use JSmath fonts" option is located in configuration.

I am beginning using Maxima after years in Derive and Matlab, and always stack into bugs, preventing me moving forward.

**Comment by Hale812** [comment]
Sorry, looks like it was fixed in the latest release.

**Comment by gunterkoenigsmann** [comment]
I would beg you to report the lack of usefullness of the description what the dialogue buttons do to http://wxWidgets.org: The dialog's intent is to inform the user that something that isn't too bad went wrong - and it offers to crash the program which means that an eventual debugger takes control and lets you see what lead to this problem. Just press "Abort" and it won't bother you again.

The actual problem is that the font you have currently selected lacks vital characters. Which I suspect to be an error on Microsoft's side.

**Comment by gunterkoenigsmann** [comment]
Just seen your comment.

...in the newest release if Microsoft fails to deliver a few characters with the default font on some systems wxMaxima falls back to use linux-libertine: This font is quite complete.

I still wonder why Arial lacks a few characters on some systems, though...
