### ISSUE TITLE
Error installing latest (5.41.0a)Maxima+wxMaxima for Winx64 package

### ISSUE THREAD

**Issue by Hale812** [andrejv/wxmaxima#980]
![image](https://user-images.githubusercontent.com/25519954/37130663-db9cbc6a-22c7-11e8-94e7-38b5d2d83f02.png)

When pushing "ignore", errors do not stop appearing

![image](https://user-images.githubusercontent.com/25519954/37130752-3e70e0e6-22c8-11e8-98d5-d6a3870d2088.png)

![image](https://user-images.githubusercontent.com/25519954/37130756-4fe79748-22c8-11e8-884d-9a11ddb9650c.png)

Probably, the bug is in dysfunctional privileges elevation part of the code. The installer, obviously, should capture dedicated installer, administrator or system privileges, before writing to "program files"

To be clear, the current user is from local administrator group, but not an administrator of the domain, where the system is logged in. So, it is possible, the code incorrectly handles domain environment data.

Starting the installer with Admin privileges manually worked.

**Comment by gunterkoenigsmann** [comment]
That might be a design decision in Windows: If a file is still used by the indexer (that generates a list of words for the search function), the virus scanner or an currently opened program it cannot be overwritten.

On linux in this case a new file with the same name is created and the old file's refcount is reduced by one (for every directory or program that currently uses the file the refcount is increased by 1). Once the refcount of a file reaches 0 it is removed. 

But I might be wrong here: I am no expert on Windows. But I know that maxima+wxMaxima normally don't need a admin account for being installed.

That means: As far as I know Maxima's installer doesn't attempt to elevate any privilleges as many users don't have any privilleges one can elevate to. Instead it hopes to have write access to the directory maxima+wxMaxima are installed to.

**Comment by daute** [comment]
If you install in the default location C:\maxima-5.41.0a (or not in a "system directory" like "C:\Program Files\...") Maxima does not require Admin privileges.
If you want to install there you have to use Admin privileges (right click -> start as admin) - as you did.
Best regards, Wolfgang

**Comment by Hale812** [comment]
I got your opinion. But from my experience, it is a "good tradition",  offering user to elevate privileges before installation. It was always this way since Windows XP, or probably NT3 (while it was not really necessary those days).

**Comment by daute** [comment]
It's not easy as an Maxima/wxMaxima developer. Some people complain because one requires admin privileges (https://sourceforge.net/p/maxima/support-requests/49/), some people complain, because one does not require them.  :smiley:

I think, we should keep it as we do now (no privileges required), I will add a note to the release notes of the next release, that one can start with right mouse click -> start as administrator, if installation to system directories is done.

Best regards, Wolfgang

**Comment by Hale812** [comment]
The most ridiculous excuse for laisiness in changing installer configuration I ever heard. 
More ridiculous is advocating by "universities with no rights". In the donain with no rights, you can not install to standard path in any way, either asked for elevation or not. The same way, denying rights elevation does not prevent installing to unsecure path, if the software can handle this allocation at all. Office, photoshop use shared system folders, thats why elevation is essential there. Maxima do not require that.
I have never seen any SANE person, complying when given free choise to do, or not to do.

**Comment by gunterkoenigsmann** [comment]
I can acknowledge that the rights management in MS Windows is ridiculous: As you have stated It makes installing things in the default paths a no-go in many universities and firms without really increasing security. I also can acknowledge that in an operating system that cannot decide if to use unicode or a local codepage and that notoriously has problems with spaces in filenames to set the default path to c:\Programs in America, but to a localized name in all other country that might use Unicode or Codepage characters and spaces.

The only thing one might be able to do is to convince Nullsoft that the installer NSIS builds should automatically acquires Administrator rights if the install path needs them and not to try to acquire them if they aren't necessary. 

I assume you actually have a good chance in getting them do so => I thank you in advance for your efforts and close this ticket, not, because it is a bad idea to dynamically determine if admin rights are needed or not, but because the real solution (even in the case a local workaround would be possible) can only be implemented from within a different project than this one.
