### ISSUE TITLE
I can not graph values lower than 10^{-9}

### ISSUE THREAD

**Issue by vicbahapad** [andrejv/wxmaxima#992]
I am trying to graph any function, for example x + 1, between 0 and 1E-10, but I get an error and the graph does not appear.
I have realized that I can graph values of the axes between 1E-1 to 1E-8, but when I graph 1E-9 onwards, I do not get any graph

**this is the error:**
wxplot2d([x+1], [x,0,1.0E-9]);
Message from maxima's stderr stream: "C:/Users/user1/maxout8152.gnuplot", line 130: Can't plot with an empty x range!

I am using the 16.04.2 version of wxmaxima on windows 7 (I think it's the latest version for windows..?)

**Comment by gunterkoenigsmann** [comment]
This error has been fixed in the version you can find at https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.41.0-Windows/

The problem was that gnuplot by default treats all numbers up to 1e-9 as "0" in order to mask rounding errors. The new version of maxima tells it no more to do so.
---
If you have more than one maxima version installed at the same time in the "maxima" tab of the config dialogue you need to tell wxMaxima which maxima.bat to use.

**Comment by gunterkoenigsmann** [comment]
Wow... ...sorry for printing half of my message this big: Seems like I accidentally have triggered some markdown.
