### ISSUE TITLE
Missing scroll bar in "tips of the day" dialog

### ISSUE THREAD

**Issue by guraga** [andrejv/wxmaxima#993]
wxMaxima 18.02.0 in ubuntu 16.04 from ppa http://ppa.launchpad.net/blahota/wxmaxima/ubuntu.

Some texts in "tips of the day" dialog not visible. Please, add scroll bars.

**Comment by gunterkoenigsmann** [comment]
Sorry for the long delay: Seems I have missed the e-mail with your bug report.

And unfortunately you have found another thing wxMaxima cannot help against too much: The Tip-of-the-day dialog is provided by wxWidgets - so the bug needs to be fixed there.

On the other hand: If you file a bug report at https://trac.wxwidgets.org/ and if they fix the problem (they normally do if gnome doesn't hinder them from doing so) this will repair hundreds of apps at once. I wouldn't be too unhappy if you were willing to file a ticket for the configuration dialogue there, too, for the same reason.

Will close this ticket for wxMaxima - not because it is invalid (it isn't) but because it needs to be resolved in a different project.
